[package]
name = "qoi-fast"
version = "0.2.0"
description = "VERY fast encoder/decoder for QOI (Quite Okay Image) format"
authors = ["Ivan Smirnov <rust@ivan.smirnov.ie>"]
edition = "2018"
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/aldanor/qoi-fast"
homepage = "https://github.com/aldanor/qoi-fast"
documentation = "https://docs.rs/qoi-fast"
categories = ["multimedia::images", "multimedia::encoding"]
keywords = ["qoi", "graphics", "image", "encoding"]
exclude = [
    "assets/*",
]

[dependencies]
bytemuck = "1.7"

[workspace]
members = ["qoi-bench"]

[dev-dependencies]
anyhow = "1.0"
png = "0.17"
walkdir = "2.3"

[lib]
name = "qoi_fast"
path = "src/lib.rs"

[profile.test]
opt-level = 3
