[package]
name = "qoi-fast"
version = "0.0.1"
description = "Fast encoder/decoder for QOI (Quite Okay Image) format"
authors = ["Ivan Smirnov <rust@ivan.smirnov.ie>"]
edition = "2021"
readme = "README.md"
license = "MIT"
repository = "https://github.com/aldanor/qoi-fast"
homepage = "https://github.com/aldanor/qoi-fast"
documentation = "https://docs.rs/qoi-fast"
categories = ["multimedia::images", "multimedia::encoding"]
keywords = ["qoi", "graphics", "image", "encoding"]
exclude = [
    "benches/*",
    "assets/*",
]

[dev-dependencies]
png = "^0.17.2"

[target.'cfg(bench)'.dev-dependencies]
# to activate, pass RUSTFLAGS="--cfg bench" until cargo does this automatically
criterion = "^0.3.5"

[lib]
name = "qoi_fast"
path = "src/lib.rs"
bench = false

[[bench]]
name = "bench"
harness = false
